services:
  - type: web
    name: django-backend
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: ""
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: your-production-secret-key
      - key: DJANGO_ALLOWED_HOSTS
        value: your-subdomain.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: your-render-db-name
          property: connectionString
