services:
  - type: web
    name: django-backend
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: ""
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "Op3DUZufsFe4CUR6Kmrdu8alhPa4Jcw8xl4RFCc9I8upk1yOBUsuLT4LdP30HMfyGfc"
      - key: DJANGO_ALLOWED_HOSTS
        value: login-monit-alert-system.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: login-monit-alert-system-db
          property: connectionString
